apiVersion: apps/v1
kind: Deployment
metadata:
  name: zepto-deployment
  labels:
    app: zepto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zepto
  template:
    metadata:
      labels:
        app: zepto
    spec:
      containers:
      - name: zepto-container
        image: danduniharika30/zepto:6bfee260
        ports:
        - containerPort: 80
